# 相关配置说明
  # favicon: 网站图标
  # avatar: 主题用户头像与昵称
  # rss: rss订阅
  # gtag: Google 分析
  # comments: 文章评论系统
    # gitalk
    # disqus
  # navbar: 主题页面导航栏
  # catalog: 文章目录
  # prevnext: 文章末尾的上一页与下一页
  # friends: 友链
  # footer: 页脚信息
  # search: 文章搜索

# enable: 是否开启相应功能，可选true || false

# 网站图标
favicon:
  enable: true
  icon: /images/icons8-espresso-cup-100-newest.png
  touch_icon: /images/icons8-espresso-cup-100-newest.png

# 用户头像与昵称
avatar:
  author_photo: /images/seth-datathon-square2.jpg
  author_nickname: sethmachine
  path: /

# Google 分析
# https://analytics.google.com
# 注册Google分析账号，在管理/创建媒体资源/选择网站/填写相关信息后得到跟踪Id，一般格式为UA-xxxxxxx-x
# 如之前已有注册账号，在管理/跟踪信息/跟踪代码/找到跟踪ID，一般格式为UA-xxxxxxx-x
gtag:
  enable: true
  gtagkey: G-FG2L3F19SM

# 文章评论系统
comments:
  enable: true
  # 目前仅支持gitalk, valine, disqus评论，选择喜欢的一种开启即可

  gitalk:
    # https://github.com/gitalk/gitalk#usage查看官方教程
    enable: false
    clientID:
    clientSecret:
    repo:
    owner:
    admin:
    id: location.pathname
    distractionFreeMode: false

  valine:
    # https://valine.js.org/quickstart.html#%E8%8E%B7%E5%8F%96APP-ID-%E5%92%8C-APP-Key
    # 进入以上网址查看官方教程
    enable: false
    appId:
    appKey:
    placeholder: Welcome!
    avatar: retro
    vempty_display: false

  # disqus 需科学上网方可使用
  disqus:
    # https://disqus.com/
    # 注册账号，获取shortname.disqus.com，shortname为你定义的唯一name
    # 例：我注册配置完毕后的网址为zxcxxxx.disqus.com，zxcxxxx即为shortname
    enable: true
    shortname: sethmachine01

# 主题页面导航栏
navbar:
  -
    name: Blog
    enable: true
    path: /
    key: home
  -
    name: About
    enable: true
    path: /about/
    key: about
  -
    name: Archives
    enable: false
    path: /archives/
    key: archives
  -
    name: Tags
    enable: true
    path: /tags/
    key: tags
#  -
#    name: Categories
#    enable: true
#    path: /categories/
#    key: categories
#-
#      name: Tags
#      enable: true
#      path: /tags/
#      key: tags
#  -
#    name: Friends
#    enable: true
#    path: /friends/
#    key: friends

# 文章目录
catalog:
  enable: true

# 文章末尾的上一页与下一页
prevnext:
  enable: true

# 友链详细信息：支持多个友链
friends:
  # nickname: 昵称
  # site: 地址
  # meta: 描述
  -
    nickname: Zcheng
    site: https://zcheng.site/
    meta:
  -
    nickname: Hexo
    site: https://hexo.io/
    meta:

# 页脚信息
footer:
  # social: 社交方式
  # more: 更多页脚信息
  social:
    # name: 名称
    # icon: 图标，目前仅支持IconFont部分图标
    # path: 地址
    -
      name: github
      icon: github
      path: https://github.com/sethmachine
    -
      name: email
      icon: envelope
      path: sdworman@brandeis.edu
#    -
#      name: facebook
#      icon: facebooksquare
#      path:
#    -
#      name: twitter
#      icon: twitter
#      path:
#    -
#      name: wechat
#      icon: wechat
#      path:
#    -
#      name: weibo
#      icon: weibo
#      path:
#    -
#      # rss需安装 hexo-generator-feed 插件
#      # 具体参照https://github.com/hexojs/hexo-generator-feed
#      name: rss
#      icon: rss
#      path: /atom.xml

  more:
    -
      name: Copyright © sethmachine 2021
      path: https://github.com/zchengsite/hexo-theme-oranges
    -
      name: Theme by Oranges | Powered by Hexo
      path: https://github.com/zchengsite/hexo-theme-oranges

    -
      name: Espresso Cup icon by Icons8
      path: https://icons8.com/icons/set/espresso-cup

# 文章搜索
search:
  enable: false
  placeholder: 
